sudo: required
dist: trusty
language: clojure
script: lein doo chrome-headless tests once
addons:
  chrome: stable
notifications:
  email:
    recipients:
      - filip@district0x.io
    on_success: change # default: change
    on_failure: change # default: always
